### ISSUE TITLE
Allow filters to be used in concert.

### ISSUE THREAD

**Issue by chuckharmston** [chuckharmston/testpilot-contribute#10]
Currently, setting one filter unsets the other. We should be smarter about this, allowing both filters to be used in concert and restricting the values of the other to prevent 0-result filter combinations.

**Comment by pdehaan** [comment]
@chuckharmston Does this mean we could filter by 2+ projects, or just 0-1 projects and 0-1 skills?

**Comment by chuckharmston** [comment]
0-1 of each. This is fixed!
