### ISSUE TITLE
Great Job, permission to use.

### ISSUE THREAD

**Issue by PikioopSo** [chuckharmston/testpilot-contribute#14]
I would like to use this as a framework for [Pi Reels Contributing App](https://github.com/PiReel/PiReel-Contributing).  Please, let me know if their are any problems with that. The Pi Reel project recently took part in Mozilla Sprint and hopes it will be accepted to the Moz Fest this year too.

Regards,
Steve

**Comment by chuckharmston** [comment]
Please do! It's licensed under the [MPL 2.0](https://github.com/chuckharmston/testpilot-contribute/blob/master/LICENSE).
