### ISSUE TITLE
Remove Screenshots?

### ISSUE THREAD

**Issue by pdehaan** [chuckharmston/testpilot-contribute#17]
Page Shot/Screenshots has been semi-retired. Should we exclude it from this site?

<img width="251" alt="firefox_test_pilot_-_contribute" src="https://user-images.githubusercontent.com/557895/29143467-28bcdb42-7d0a-11e7-9246-ed86c08e2e57.png">

Same with Activity Stream: https://github.com/chuckharmston/testpilot-contribute/blob/8f5732ae3623c6ab4d87f11919ec54dda0a083c2/src/config.json#L98-L117

**Comment by chuckharmston** [comment]
I think it's fine to leave them here for now; they're still projects that the Test Pilot team is working on.
