### ISSUE TITLE
Add missing footer link HREFs

### ISSUE THREAD

**Issue by pdehaan** [chuckharmston/testpilot-contribute#19]
https://github.com/chuckharmston/testpilot-contribute/blob/f6106ab8cb1cd611b93d060c95b4fe606310a4e0/src/components/footer/index.js#L8-L25

**Comment by CHBaker** [comment]
I'll take this task, are the pages already built?

**Comment by chuckharmston** [comment]
Ack, sorry @CHBaker! I pushed a fix for it before seeing this bug (via https://github.com/mozilla/testpilot/issues/2687#issuecomment-321359308).

If you're looking to get your feet wet, I fortunately know just the place :wink:: https://contribute.testpilot.firefox.com/tasks/

**Comment by pdehaan** [comment]
Chuck, at the risk of sounding a bit circular, should we have "good-first-bugs" on this repo, and add them to the site? Or is that too meta?

**Comment by chuckharmston** [comment]
>Chuck, at the risk of sounding a bit circular, should we have "good-first-bugs" on this repo, and add them to the site? Or is that too meta?

I've thought about that! But this will likely end up in Test Pilot some time soon, so I didn't go overboard with it.

**Comment by pdehaan** [comment]
> But this will likely end up in Test Pilot some time soon, so I didn't go overboard with it.

Depending on your timing of migrating this to something like testpilot.firefox.com/contribute, you may want to smite down this issue: https://github.com/mozilla/testpilot/issues/2757
