### ISSUE TITLE
Remove Containers repo

### ISSUE THREAD

**Issue by pdehaan** [chuckharmston/testpilot-contribute#41]
We're graduating the Containers experiment, so we probably want to remove it from the Contribute site:

https://github.com/mozilla/testpilot/blob/f9aad957f5dbe6b0484efe275158e17eac68e4bf/content-src/experiments/containers.yaml#L118

https://testpilot.dev.mozaws.net/experiments/containers

**Comment by chuckharmston** [comment]
Fixed in 845ca25.
