### ISSUE TITLE
Add button to reset filters.

### ISSUE THREAD

**Issue by chuckharmston** [chuckharmston/testpilot-contribute#9]

**Comment by pdehaan** [comment]
Me thinks this is done, no?

<img width="226" alt="firefox_test_pilot_-_contribute" src="https://user-images.githubusercontent.com/557895/29144186-d7967ea0-7d0c-11e7-8b0b-90383480c436.png">

Plus the reset link when your filters return zero results:

<img width="853" alt="firefox_test_pilot_-_contribute" src="https://user-images.githubusercontent.com/557895/29144220-fbdcade8-7d0c-11e7-84e9-d6c0ea03f971.png">
